package ru.nivanov.jrbuilder.forms;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import ru.nivanov.jrbuilder.report.Report;
import ru.nivanov.jrbuilder.report.ReportLoader;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.io.IOException;

/**
 * @author nivanov
 *         on 02.08.17.
 */
public class LoadForm {
    private JButton loadReportButton;
    private JButton createReportButton;
    private JPanel loadForm;

    private LoadForm() {
        ReportLoader reportLoader = new ReportLoader();
        JFileChooser fc = new JFileChooser();
        createReportButton.addActionListener(e -> {
            FileNameExtensionFilter filter = new FileNameExtensionFilter("JasperReport files", "jrxml");
            fc.setFileFilter(filter);
            int retVal = fc.showSaveDialog(createReportButton);
            if (retVal == JFileChooser.APPROVE_OPTION) {
                try {
                    String filePath = fc.getSelectedFile().getPath();
                    if (!filePath.endsWith(".jrxml"))
                        filePath += ".jrxml";
                    reportLoader.createNewReport(filePath);
                    Report report = reportLoader.loadReport(filePath);
                    new ReportForm(report);
                } catch (IOException e1) {
                    e1.printStackTrace();
                }
            }
        });

        loadReportButton.addActionListener(e -> {
            int retVal = fc.showOpenDialog(createReportButton);
            if (retVal == JFileChooser.APPROVE_OPTION) {
                Report report = reportLoader.loadReport(fc.getSelectedFile().getPath());
                new ReportForm(report);
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("JRBuilder");
        frame.setContentPane(new LoadForm().loadForm);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        loadForm = new JPanel();
        loadForm.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        loadReportButton = new JButton();
        loadReportButton.setText("Загрузить отчет");
        loadForm.add(loadReportButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        createReportButton = new JButton();
        createReportButton.setText("Создать новый отчет");
        loadForm.add(createReportButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return loadForm;
    }
}
